name: Pages

on:
  push:
    branches:
      - main # 默认分支

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # 使用最新版本的 checkout action

      - name: Set up Node.js 16.20.1
        uses: actions/setup-node@v3 # 使用最新版本的 setup-node action
        with:
          node-version: "16.20.1"

      - name: Cache NPM dependencies
        uses: actions/cache@v3 # 使用最新版本的 cache action
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Install Dependencies
        run: npm ci # 使用 npm ci 代替 npm install，确保依赖安装更可靠

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public